blank_issues_enabled: true
contact_links:
    - name: zksync-developers Discussion
      url: https://github.com/zkSync-Community-Hub/zksync-developers/discussions
      about: Please provide feedback, and ask questions here.